#!/usr/bin/env python
import json
import os
import subprocess
from tkinter import *

root_path = os.path.dirname(os.path.abspath(__file__)).replace('\\', '/')
config_file = f'{root_path}/config.json'

with open(config_file) as file:
    config = json.load(file)


font_family = config['font']['family']
font_size = config['font']['size']
background = config['background']
foreground = config['foreground']
cursor_color = config['cursorColor']
suggestion_color = config['suggestionColor']


root = Tk()
root.overrideredirect(True)
command = Entry(root, background=background, foreground=foreground,
                width=root.winfo_screenwidth(), insertbackground=cursor_color, font=(font_family, font_size))
command.pack()
command.focus()


def close(event = None):
    root.destroy()


def run(event = None):
    if command.get() == '':
        exit()
    else:
        subprocess.Popen(command.get())

    close()


root.bind("<Escape>", close)
root.bind("<Return>", run)

root.mainloop()
