#!/usr/bin/env python
import subprocess
from tkinter import *
import json
import pathlib

config_file = f'{pathlib.Path.home()}/.config/.dmenurc'

with open(config_file) as file:
    config = json.loads(file.read())

fontFamily = config['font']['family']
fontSize = config['font']['size']
bg = config['background']
fg = config['foreground']
cursorColor = config['cursorColor']
suggestionColor = config['suggestionColor']


root = Tk()
root.overrideredirect(True)
command = Entry(root, background=bg, foreground=fg,
                width=root.winfo_screenwidth(), insertbackground=cursorColor, font=(fontFamily, fontSize))
command.pack()
command.focus()


def close(event):
    root.destroy()


def run(event):
    subprocess.Popen(command.get())
    root.destroy()


root.bind("<Escape>", close)
root.bind("<Return>", run)

root.mainloop()
